# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
#- task: AzureFileCopy@4
#  inputs:
#    SourcePath: '$(Pipeline. Workspace)'
#    azureSubscription: 'ARM RSG service connection'
#    Destination: 'AzureBlob'
#    storage: 'armtemplatedeployment'
#    ContainerName: 'armtemplate'
#  name: AzureFileCopy


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARM RSG service connection'
    subscriptionId: '3bfbed38-73ee-486e-b212-d758a975a66c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARM'
    location: 'Central India'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://armtemplatedeployment.blob.core.windows.net/armtemplate/template.json?sp=r&st=2022-11-23T16:22:31Z&se=2022-11-24T00:22:31Z&spr=https&sv=2021-06-08&sr=b&sig=CB%2BfjjoUu5GHIyFvf5gHjUaQXJlDAm2I6wK9Bld9xRw%3D'
    csmParametersFileLink: 'https://armtemplatedeployment.blob.core.windows.net/armtemplate/parameters.json?sp=r&st=2022-11-23T16:10:47Z&se=2022-11-24T00:10:47Z&spr=https&sv=2021-06-08&sr=b&sig=WZqN1F8yDdrUGj4bOpyEVojfNDYFzj9Q6yegfEBHdVc%3D'
    deploymentMode: 'Incremental'
